version: '3'
services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - '${WEBSITE_IMAGE}'
    image: '${WEBSITE_IMAGE}'
    ports:
      - '3000:3000'
    volumes:
      - website:./website/build/ # build files will be added at this directory !!!

volumes:
  website: